### ISSUE TITLE
D1 and D2 fail to build on Linux after 86adfc0

### ISSUE THREAD

**Issue by adolfogp** [dxx-redux/dxx-redux#126]
While D1 and D2 build successfully in Windows using Visual Studio 2022 (up to the latest commit - d891e79), changes introduced in 86adfc0 break the build on Linux. I'm using GCC 13.3.0 on Ubuntu 24.04.1 LTS (Noble Numbat) and reverting 86adfc0 fixes the build issues. The core of the problem seems to be the use of `sprintf_s` and `strcpy_s` in [`newdemo.c`](https://github.com/dxx-redux/dxx-redux/blob/main/d1/main/newdemo.c)

```
/home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3263:(.text+0xfa9): undefined reference to `sprintf_s'
/usr/bin/ld: /home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3269:(.text+0x100c): undefined reference to `sprintf_s'
/usr/bin/ld: /home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3283:(.text+0x1058): undefined reference to `sprintf_s'
/usr/bin/ld: /home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3281:(.text+0x108a): undefined reference to `sprintf_s'
/usr/bin/ld: /home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3287:(.text+0x10b5): undefined reference to `sprintf_s'
/usr/bin/ld: CMakeFiles/d1x-redux.dir/newdemo.c.o:/home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3296: more undefined references to `sprintf_s' follow
/usr/bin/ld: CMakeFiles/d1x-redux.dir/newdemo.c.o: in function `newdemo_get_default_filename':
/home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3289:(.text+0x112c): undefined reference to `strcpy_s'
/usr/bin/ld: /home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3252:(.text+0x1162): undefined reference to `sprintf_s'
/usr/bin/ld: /home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3254:(.text+0x1184): undefined reference to `sprintf_s'
/usr/bin/ld: CMakeFiles/d1x-redux.dir/newdemo.c.o: in function `newdemo_prompt_filename':
/home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3304:(.text+0x1248): undefined reference to `strncpy_s'
/usr/bin/ld: /home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3334:(.text+0x137c): undefined reference to `strcpy_s'
/usr/bin/ld: CMakeFiles/d1x-redux.dir/newdemo.c.o: in function `newdemo_stop_recording':
/home/adolfo/CLionProjects/dxx-redux/d1/main/newdemo.c:3364:(.text+0x146e): undefined reference to `sprintf_s'
collect2: error: ld returned 1 exit status
gmake[2]: *** [main/CMakeFiles/d1x-redux.dir/build.make:1197: main/d1x-redux] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:410: main/CMakeFiles/d1x-redux.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by SiriusTR** [comment]
These functions were added to the C standard in C11, so my guess is that CMake hasn't configured GCC to use that. Not sure what changes are needed, trying to figure that out...
